services:

  web1:
    build: apache
    container_name: ubuntu_22_apache_php1
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
      - ./apache/proxy.conf:/etc/apache2/sites-enabled/000-default.conf
    links: 
      - db1:db1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"

  db1:
    image: mariadb:10.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb-home/uploads:/home/uploads
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"
    networks:
      - backend
      
networks:
  backend:
    driver: bridge